<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Coach App</title>
 <!-- CSS -->

        <link rel="stylesheet" href="/lt/css/bootstrap.min.css">
        <link rel="stylesheet" href="/lt/css/font-awesome.min.css">
        <link rel="stylesheet" href="/lt/css/main.css">
        <link rel="stylesheet" href="/lt/css/animate.css">
        <link rel="stylesheet" href="/lt/css/responsive.css">
        

        <!-- Js -->
        <script src="/lt/js/vendor/modernizr-2.6.2.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="/lt/js/bootstrap.min.js"></script>
        <script src="/lt/js/plugins.js"></script>
        <script src="/lt/js/main.js"></script>
        <script src="/lt/js/wow.min.js"></script>
        <script src="/js/sei.js"></script>
        <script src="/js/seiApi.js"></script>
        <script>
         new WOW(
            ).init();
        </script>

</head>

<body class="body-wrapper">
	<header>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-xs-6 col-sm-3">
                    <a href="#" class="logo">
                       <!-- <img width="105" src="/lt/images/logo.png" alt=""> -->
                    </a>
                </div>
                <div class="col-md-6 col-xs-6 col-sm-6">
                    <div class="menu">
                        <nav class="navbar navbar-default" role="navigation">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    </button>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a href="/">Home</a></li>
                                        <li><a href="/privacy">Privacy</a></li>
                                        <li><a href="/terms">Terms of use</a></li>
                                        <li><a href="/account/log/in">Sign In</a></li>
                                        <li><a href="/account/log/out">Sign Out</a></li>
                                    </ul>
                                  
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12 col-sm-3">
                    <ul class="social-info">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <!-- 
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        -->
                    </ul>
                </div>
            </div>
        </div>
    </header>
    
<?php echo $this->content; ?>

    <footer class="wow fadeInUp" data-wow-delay=".8s">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-12">
                        <a class="footer-logo"href="#">
                            <!--  <img class="" width="150" src="/lt/images/footer-logo.png" alt=""> -->
                        </a>

                    <p>Copyright © 2019 CoachApp.</p>
                    
                </div>
            </div>
        </div>
    </footer>
<?= $this->inlineScript() ?>
</body>
</html>
