<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Sign In</title>
	
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />


	<?php /** echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
	->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
	->appendStylesheet($this->basePath() . '/css/jq.ui/smoothness/jq.ui.1.8.23.min.css')
	->appendStylesheet($this->basePath() . '/js/jq_tables/demo_table_jui.css')
	->appendStylesheet($this->basePath() . '/css/backend/style.css')
		->appendStylesheet($this->basePath() . '/css/forms.css');**/


    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->appendStylesheet($this->basePath() . '/theme/bower_components/bootstrap/dist/css/bootstrap.min.css')
    ->appendStylesheet($this->basePath() . '/theme/bower_components/font-awesome/css/font-awesome.min.css')
    ->appendStylesheet($this->basePath() . '/theme/bower_components/Ionicons/css/ionicons.min.css')
    ->appendStylesheet($this->basePath() . '/theme/dist/css/AdminLTE.min.css')
    ->appendStylesheet($this->basePath() . '/theme/plugins/iCheck/square/blue.css');
    
    
	echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->appendFile($this->basePath() . '/js/jq.1.8.min.js')
		->appendFile($this->basePath() . '/js/jq.ui.1.8.23.min.js')
		->appendFile($this->basePath() . '/theme/bower_components/jquery/dist/jquery.min.js')
		->appendFile($this->basePath() . '/theme/bower_components/jquery-ui/jquery-ui.min.js')
		->appendFile($this->basePath() . '/theme/bower_components/bootstrap/dist/js/bootstrap.min.js')
		->appendFile($this->basePath() . '/theme/plugins/iCheck/icheck.min.js');
		?>

</head>
</head>

<body>
	
		<?php echo $this->content; ?>



<!-- FOR CUSTOM STYLES -->
<div class="styles"></div>
</body>
</html>
