<div class="container-fluid settings-container">
			<div class="main-content-settings">						
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="heading-simple">
								<h3 class="section-title">Offer</h3>
							</div>
							<div class="content">
							
							
			<div class="container2">
				<div class="row flexx">
					<div class="col-sm-6 company-info">
						<h4>Company Info</h4>
						<div class="form-group">
							<label class="btn-block"><?php echo $this->inv->getMapper()['orgName'];?></label>
						</div>
						<div class="form-group">
							<label class="btn-block"><?php echo $this->inv->getMapper()['orgAddress'];?></label>
						</div>
						<div class="form-group">
							<label class="btn-block"><?php echo $this->inv->getMapper()['orgCity'];?>, <?php echo $this->inv->getMapper()['orgCountry'];?></label>
						</div>
					</div>
					<div class="col-sm-6 text-center">
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-sm-12">
						<h3>Project: <b><?php echo $this->inv->getProjectName();?></b></h3>
					</div>
					<hr>
					<div class="col-sm-12 table-view-price">
						<div class="row thh">
							<div class="col-sm-6">Group name</div>
							<div class="col-sm-4">Working hours</div>
							<div class="col-sm-2">Cost</div>
						</div>
					<?php foreach($this->inv->getProject()->getGroups() as $group):?>
						<div class="row tdd">
							<div class="col-sm-6"><?php echo $group->getMapper()['name'];?></div>
							<div class="col-sm-4"><?php echo $group->getWorkingHours();?>h</div>
							<div class="col-sm-2"><?php echo $group->getPrice();?> €</div>
						</div>
					<?php endforeach;?>
						<div class="row tdd">
							<div class="col-sm-6">&nbsp;</div>
							<div class="col-sm-2">&nbsp;</div>
							<div class="col-sm-4"><b>Total</b> <span class="offer-price"><?php echo $this->inv->getProject()->getPrice();?> €</span></div>
						</div>
					</div>
					<div class="col-sm-12">
					</div>
				</div>
				<div class="row offer-lists">
					<div class="col-sm-9">
						<h4 class="mrgT30 project-groups-titlee">Project groups</h4>
						<div class="row">	
							<div class="col-sm-4 offer-lists-title">
								<div class="temp-title">Project timeline</div>
								
					<?php foreach($this->inv->getProject()->getGroups() as $group):?>
							<h5><?php echo $group->getMapper()['name'];?> (<?php echo $group->getWorkingHours();?>h)</h5>
					<?php endforeach;?>
					
							</div>
							<div class="col-sm-8 chartt-over">
								<div class="horizontal rounded">
								
							<?php foreach($this->inv->getProject()->getGroups() as $group):?>
								  <div class="progress-barr horizontal">
									<div class="progress-track">
									  <div class="progress-fill" style="background: rgba(43, 124, 181, 1)">
										<span data-start="<?php echo $group->getStartPercent();?>%"><?php echo $group->getPercent();?>%</span>
									  </div>
									</div>
								  </div>
							<?php endforeach;?>
							
								  <div class="offers-timeline-dates">
								  
								<?php foreach($this->inv->getProject()->getGroups() as $group):?>
									<span data-percent="<?php echo $group->getStartPercent();?>" class="offer-date" style="left: 0"><?php echo $group->getStartDate();?></span>
								<?php endforeach;?>
								
								  </div>

								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="offer-lists-title" style="padding-top: 65px">
						
						<?php foreach($this->inv->getProject()->getGroups() as $group):?>
							<h4><?php echo $group->getPrice();?> €</h4>
						<?php endforeach;?>
						
						</div>
					</div>
				</div>
				<div class="row mrgB50">
					<div class="col-sm-12">

					</div>
					
					<div class="col-sm-12 text-right">
					</div>
				</div>
			</div>
			
			
			
			
			</div>
			</div>
			</div>
			</div>
			</div>
</div>