 <div class="one_wrap" style="display: table; width: 50%; margin: 0 auto;">
                <div class="widget">
                    <div class="widget_title"><span class="iconsweet"></span>
                        <h5><?php  echo $this->translate('Privacy Policy', __NAMESPACE__);?></h5>
                    </div>
                    <div class="widget_body">
                        <div class="content_pad">
            <article>
                <h3>THANK YOU FOR USING WORKMARK!</h3>
                <p>Workmark is a local app built for teams. Using this app you can organize your team work.</p>
            </article>
            <article>
                <h3>ACCOUNT INFORMATION</h3>
                <ul>
                    <li><span>In Profile settings, you can control what information you share with people via your

profile, including username and bio.</span></li>
                   
                </ul>
            </article>
            <article>
                <h3>HOW IS INFORMATION COLLECTED?</h3>
                <p><strong>When you give us permissions to obtain it</strong>. When you sign up for or use our products, you voluntarily give us certain information. This can include your name, profile photo, email address you used to sign up, and any other information you provide us.</p>
                
            </article>
            <article>
                <h3>HOW DO WE USE INFORMATION WE COLLECT?</h3>
                <p><strong>How Do We Use Personally Identifiable Information (PII)</strong>? We are using your email address only as your unique ID, so you can log in to the app even without facebook, using your email and password. We do NOT share any of your information with no one.</article>
            <article>
                <h3>IMPORTANT THINGS TO KEEP IN MIND:</h3>
                <p><strong>Changing Our Policy</strong>. This Privacy Policy is subject to change. We will prominently post a notice on the Site when there are material changes in the way we treat PII. You should periodically check back and review this Privacy Policy so that you always will know what information we collect, how we use it, and with whom we share it.</p>
            </article>
            <article>
                <h3>MISCELLANEOUS</h3>
                <p>
                    Please <a href="/account/legal/contact" data-bypass="true">contact us</a> to report Abuse or Violation of this Privacy Policy.
                    </p>
            </article>
                <p>
                    <a href="/account" data-bypass="true">Go to log in page</a>
                </p>
		</div>
	</div>
</div>
</div>