<?php if($this->status):?>
    <?php if($this->status == "success"):?>
    <div class="callout callout-success">
                <h4>Success!</h4>
                <p>The data has been successfully updated.</p>
              </div>
    <?php else:?>
    <div class="callout callout-danger">
                <h4>Error!</h4>
                <p><?php echo $this->status;?>.</p>
              </div>
    <?php endif;?>

<?php endif;?>

<div class="row">
        <div class="col-xs-12">
           <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><?php echo $this->team->team_name;?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="" method="post">
              <div class="box-body">
                <div class="form-group">
                  <label for="team_name">Team Name</label>
                  <input value="<?php echo $this->team->team_name;?>" name="team_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="Team Name">
                </div>
                <div class="form-group">
                  <label for="team_gender">Team Gender</label>
                  <input value="<?php echo $this->team->team_gender;?>" name="team_gender" type="text" class="form-control" id="exampleInputEmail1" placeholder="Team Gender">
                </div>
                
                <div class="form-group">
                  <label for="age_group">Team Age</label>
                  <input value="<?php echo $this->team->age_group;?>" name="age_group" type="text" class="form-control" id="exampleInputEmail1" placeholder="Age Group">
                </div>
                <!-- 
                <div class="form-group">
                  <label for="team_colors">Team Colors</label>
                  <input value="<?php echo $this->team->team_colors;?>" name="team_colors" type="text" class="form-control" id="exampleInputEmail1" placeholder="Team Colors">
                </div>
                 -->
                <div class="form-group">
                  <label for="team_description">Team Description</label>
                  <input value="<?php echo $this->team->team_description;?>" name="team_description" type="text" class="form-control" id="exampleInputEmail1" placeholder="Team Description">
                </div>
                
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>