<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Available attendees</h3>

              <div class="box-tools">
                
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="teamsTable table table-hover">
                <tr>
                  <th></th>
                  <th>Created By</th>
                  <th>Name</th>
                  <th>Requested On</th>
                  <th>Accepted</th>
                  <th>Entity</th>
                  
                </tr>
                <?php foreach($this->list as $one):?>
                <tr>
                  <td>
                	<img class="img-circle" width="25" alt="" src="<?php echo \Workmark\User\User::getImage($one);?>">
                  </td>         
                  <td>
                  <span style="font-size: 14px; float:left; clear: left; display:inline:block;"><?php echo strtoupper($one['name']);?></span>
                  </td>
                  <td>
                  <span style="font-size: 14px; float:left; clear: left; display:inline:block;"><?php echo strtoupper($one['request_name']);?></span>
                  </td>
                  <td>
                  <span style="font-size: 14px; float:left; clear: left; display:inline:block;"><?php echo \Workmark\Misc::datetimeToHuman($one['created_on']);?></span>
                  </td>
                  <td>
                  <span style="font-size: 14px; float:left; clear: left; display:inline:block;"><?php echo ($one['accepted']==0)?"NOT":"YES";?></span>
                  </td>
                  <td>
                  <span style="font-size: 14px; float:left; clear: left; display:inline:block;"><?php echo $one['entity'];?></span>
                  </td>
                  

                </tr>
                <?php endforeach;?>
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <div class="box-tools">
                <?php echo $this->pagination; ?>
              </div>
            </div>
            <!-- /.box-footer -->
            
          </div>
          <!-- /.box -->
        </div>
      </div>